### ISSUE TITLE
Login not showing any error message

### ISSUE THREAD

**Issue by RVP04** [LaravelDaily/Laravel-AdminLTE3-Boilerplate#4]
Sir,
When u do any mistake in login like wrong password or wrong username it is not showing any information in message. Can u please kindly check.

@LaravelDaily @PovilasKorop

**Comment by Marius-K** [comment]
Hello @RVP04 

Thank you for noticing the mistake. Fixed, please pull the latest version of repository.

**Comment by RVP04** [comment]
Thank you so much @Marius-K
