### ISSUE TITLE
Laravel Logger

### ISSUE THREAD

**Issue by RVP04** [LaravelDaily/Laravel-AdminLTE3-Boilerplate#5]
Sir, 

Can u please add laravel logger to this package to track for any error logs when it is in production it will be useful.

**Comment by RVP04** [comment]
Sir,

Can u please add laravel logger to this package to track for any error logs when it is in production it will be useful.

**Comment by PovilasKorop** [comment]
@RVP04 sorry we don't plan to add anything to this project, it's a boilerplate, not a full feature project
