### ISSUE TITLE
Language Pagination

### ISSUE THREAD

**Issue by maurotello** [LaravelDaily/Laravel-AdminLTE3-Boilerplate#8]
Hello! First thanks for sharing this code, it is very good and I am using it a lot. 

I have a problem with the pagination texts. For example Previous and Next, I have tried to change it by the language side, in views / lang, I have also tried to change it manually from "views / vendor / pagination /" and it is not updated either.

I made a config: cache from the console but neither does it continue to be seen in English and I want to pass it to Spanish. I really don't know what other configuration might be missing. Perhaps there is somewhere to configure this that belongs to Datatables.

Thanks!!

![pagination](https://user-images.githubusercontent.com/7535366/72683148-8a2d4100-3ab3-11ea-98f0-7c1e22699d86.png)

![Screenshot_2](https://user-images.githubusercontent.com/7535366/72683153-8dc0c800-3ab3-11ea-927f-5fe6d49478c8.png)

**Comment by maurotello** [comment]
I solved it by modifying the following code

`let languages = {
    'es': 'https://cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json'
  };`

Before there was the English language. Then on console I did

`npm run dev`

Now if the pagination happened to Spanish language. Therefore the other files mentioned are not being used it seems

**Comment by PovilasKorop** [comment]
Yes, some of those translations belong to Datatables, so your solution is correct.
