### ISSUE TITLE
Password Reset Email Not Showing success or error message

### ISSUE THREAD

**Issue by RVP04** [LaravelDaily/Laravel-AdminLTE3-Boilerplate#9]
Sir,
When we try to send password reset request via email. After clicking the reset button it showing whether email is send or any error is occured. 

Can u please help us putting the notification.

**Comment by Marius-K** [comment]
Hello @RVP04 

Thank you for noticing this issue. I've fixed it. Please pull the repository to latest version or make changes in your code following the commit 1f5731b25c4a80ace30704d3489327ada11f302f
